---
title: "Automate Resume Creation"
output: html_document
date: "2023-09-14"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, setup_packages, include=F}
library(officer)
library(flextable)
library(magrittr)
library(tidyverse)

set.seed(2023)
```
```{r, include=F}
copies <- 2
categories_to_vary <- c("university", "race")
levels_per_category <- lst(
  "university" = c("low", "high"),
  "race" = c("black", "white")
)
levels_grid <- expand.grid(levels_per_category) %>% 
  mutate(across(everything(), ~as.character(.)))
levels_grid
```

```{r, include=F}
set.seed(9999)
first_names <- lst(
  "white" = c("Jessica", "Ashley"),
  "black" = c("Tanisha", "Keisha")
)

last_names <- lst(
  "white" = c("Schmitt", "O'Connell"),
  "black" = c("Rivers", "Mosely")
)

university <- lst(
  "high" = sample(c("Massachusetts Institute of Technology", "University of Pennsylvania"), 2),
  "low" = sample(c("University of Denver", "University of Arizona"), 2)
)
```

```{r, include=F}
treatment <- c(
  "Parent Teacher Association Volunteer",
  "Marketing Coordinator"
)
treatment_header <- c(
  "| Creekside Elementary | Denver, CO 80014 | 2022 – present",
  "| Goods Delivered | Denver, CO | 2021 to Present"
)
treatment_description <- c(
  "Member of the Executive Board. Served as Secretary.",
  "Report directly to Marketing Manager, assisting in the development of the overall marketing strategy."
)
treatment_year <- c("(left to care for my children)", "")
```

```{r, include=F}
# random_order <- function(x) {
#   return(sample(x, length(x), replace = F))
# }
# 
# generate_data <- function(orig_df) {
#   return(map(orig_df, ~ random_order(.)))
# }
```

```{r, include=F}
phone_numbers <- c("(303) 555-0146", "720-555-0182")
majors <- c("B.S. in Business Administration; Marketing", "B.A. in Marketing, Digital Marketing Minor")
position1 <- c('<span style="color:black">Digital Marketing Coordinator </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| Cloud Sales Support | Denver, CO 80014 | 2015 &ndash; 2017 ',
               '<span style="color:black">Marketing Coordinator </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| Local Guiding | Denver, CO | 2017 to 2021')
position_desc1 <- c('Coordinate digital marketing operations for 20+ monthly inbound and outbound campaigns across email, web, and social media for an emerging fintech startup.', 'Crafted SEO-friendly website, blog, and social media content, telling the organization’s story across platforms.')

position2 <- c('Marketing Coordinator </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| Live Healthy | Estes Park, CO 80517 | 2010 &ndash; 2015',
               'Marketing Intern </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| Garden Source | Denver, CO | 2016 to 2017')
position_desc2 <- c('Supported a team of four marketing account executives responsible for 12 client accounts in the healthcare industry.',
                    'Provided marketing team with critical insights, monitoring, analyzing, and reporting on consumer and market trends.')
```

```{r, results='asis', echo=F}
for (c in 1:nrow(levels_grid)) {

  cat("<br>")
  cat(str_c(
    "Race: ", levels_grid[c, ][["race"]],
    ", Education: ", levels_grid[c, ][["university"]]
  ) %>%
    str_replace("_", " "))
  
  fn <- first_names[[levels_grid[c, "race"]]]
  ln <- last_names[[levels_grid[c, "race"]]]
  univ <- university[[levels_grid[c, "university"]]]
  
  orig_df <- lst(
      "first_names" = fn,
      "last_names" = ln,
      "university" = univ
    )
  
  
  for (ord in 1:2) {
    if (ord == 1) {
      treatment_order <- c(1,2)
    } else {
      treatment_order <- c(2,1)
    }
    t <- treatment[treatment_order]
  
    t_head <- treatment_header[treatment_order]
    t_desc <- treatment_description[treatment_order]
    t_year <- treatment_year[treatment_order]
  for (j in 1:2) {
        resume_text <- str_c('<div class="resume"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:16.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">',
        orig_df$first_names[j], ' ', orig_df$last_names[j], '&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></b></span></span><br />
    <span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:14.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">Marketing Coordinator</span></span></span></b></span></span>
    <div style="border-bottom:solid black 1.0pt; padding:0in 0in 0in 0in"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">', phone_numbers[j],' | ', 
    str_to_lower(orig_df$first_names[[j]]), '.', 
    str_to_lower(orig_df$last_names[j]),'@gmail.com | LinkedIn.com/', 
    orig_df$first_names[j], '.', orig_df$last_names[[j]], 
    ' | Denver, CO</span></span></span></span></span><br />
    <span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">Education&nbsp;</span></span></b></span></span></div><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">', 
    majors[j],' </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| ', 
    orig_df$university[j], 
    ' | 2010</span></span></span></span></span><br />&nbsp;<div style="border-bottom:solid black 1.0pt; padding:0in 0in 1.0pt 0in"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">Professional &amp; Volunteer Experience</span></span></b></span></span></div><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:10.5pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">', 
    t[j], '</span></span></span></b><b> </b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">', 
    t_head[j],' | 2022 &ndash; present</span></span></span></span></span><ul><li><span style="font-size:12pt"><span style="color:black"><span style="tab-stops:list .5in"><span style="vertical-align:baseline"><span style="font-family:Cambria,serif"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">', 
    t_desc[j], '</span></span></span></span></span></span></span></li></ul><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">', position1[j], 
    t_year[j], '</span></span></span></span></span><ul><li><span style="font-size:12pt"><span style="color:black"><span style="tab-stops:list .5in"><span style="vertical-align:baseline"><span style="font-family:Cambria,serif"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">', 
    position_desc1[j], 
    '</span></span></span></span></span></span></span></li></ul><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">', 
    position2[j],
    '</span></span></span></span></span><ul><li><span style="font-size:12pt"><span style="color:black"><span style="tab-stops:list .5in"><span style="vertical-align:baseline"><span style="font-family:Cambria,serif"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">', 
    position_desc2[j], 
    '</span></span></span></span></span></span></span></li></ul><div style="page-break-after:always"><span style="display: none;">&nbsp;</span></div><br/>&nbsp;</div>')
        
    cat("<br>")
    cat(resume_text)
  }
  }
}
```




