## Intro

Hello, I'm excited to present work on data-adaptive experimentation to find contexts with the most and least discrimination which is joint work with Jennah Gosciak and Ian Lundberg

## Experiments detect discrimination

- Randomized experiments have been shown to be effective tools for revealing discriminatory choices and studying preferences of decision makers
- Numerous studies have shown that discrimination based on background characteristics happens in many settings
- For example, audit studies on employment have demonstrated that
    - black job applicants with no criminal record receive call-backs at similar rates to white job applicants with criminal records
    - AND that job applicants who are non-mothers receive more than 2 times as many callbacks as equally qualified mothers.

While demonstrating that discrimination exists is important, many researchers want to go beyond this and understand the dynamics of discrimination and how it varies depending on the situation

## A new question

- We understand that discrimination and preferences may vary depending on background characteristics and context
- As a result of this, we argue that researchers *(in some cases)* should pivot to a new question that more adequately captures real-world heterogeneity
- New Q: In what settings is discrimination the most (or least) severe?

For a concrete application of this new question, we will focus on the following motivating example:

## A motivating example

- In their 2015 paper, Hainmueller and Hopkins (2015) study attitudes among U.S. citizens toward immigration applicants
- Specifically, they deploy a large-scale survey to understand how different applicant characteristics affect the likelihood of admission to the U.S.
- Respondents are shown a table (like the one below) that displays two applicant profiles that are constructed from different applicant characteristics. Respondents are then required to select one immigrant for admission to the U.S.
- Each of these characteristics can take on multiple values which results in many possible profile combinations

## Experiments also pose challenges...

- But, studying discrimination in such examples with experiments also comes with a variety of challenges.

## Conjoint design and limitations

- One potential design to study discrimination in this setting is the conjoint design, and this is actually the design that H&H adopt in their paper

- Conjoint experiments are well-suited for studying complex, multidimensional choices such as this. They measure respondents’ preferences when presented with profiles constructed from a randomized set of characteristics

- One of the recent advances in conjoints, the Average Marginal Component Effect (AMCE), allows researchers to study the causal effect of one characteristic while averaging over the distributions of all other characteristics

- Using the AMCE allows them to isolate the individual effects of applicant characteristics

- For example, they find that a bachelor’s degree increases the likelihood of admission compared to no formal education
by 20 percentage points

- AMCEs allow researchers to efficiently explore the effects of individual characteristics, but are less helpful for studying heterogeneous effects of characteristics, which is precisely what we are interested in understanding

- We want to understand how discriminatory preferences for college-educated applicants change depending on other applicant characteristics

Now, before continuing further I want to define a couple terms I'll be using through the duration of the slides

## Definitions

- The first term is *Focal Attribute*. The focal attribute is the characteristic that we manipulate to test for discrimination. In our case the focal attribute is the immigrant applicant's education level

- The other term is *context*. Context refers to each possible combination of background characteristics where discrimination may vary. In our example, the four characteristics are:
    - The immigrant's reason for application
    - Their county of origin
    - Their profession
    - And the number of prior trips they've taken to the U.S.
The full set of contexts is the set of all possible combinations of these characteristics.

Now, suppose that we want to study how education-based discrimination varies across all of these contexts...

## Optimal design and limitations

... and let's assume a very simple setup

- Where each of our four different characteristics only takes on two possible values, resulting in 16 total contexts

- However, to effectively study discrimination in all 16 contexts one would need a sufficiently large sample size to have a robustly powered study which would also incur significant cost, not to mention it may also be challenging to implement

Given these challenges we want to adjust our question to a closely related but slightly different question

## Solution - Adaptive experiments

- We no longer want to estimate discrimination in all contexts. Instead, we want to adaptively search for the context that leads to the **most** (or **least**) discrimination.
- This approach helps researchers narrow their focus to the most relevant contexts for their research question and prioritize these contexts in further experiments.
- By detecting heterogeneous discrimination, our design enables scientists and policymakers to pinpoint situations where discrimination is most and least likely to occur.

- Traditional randomized and conjoint experiments have limitations in this setting, which we address by data-adaptively allocating future samples to contexts using an adaptive design.

## Adaptive design (1)

- To achieve this, we build directly on work by Offer-Westort, and co-authors (among others). 
- We frame our experiment as a Multi-arm Bandit problem where each of our 16 contexts is an arm
- We use the classic Thompson sampling algorithm to allocate respondents to context.
- Each respondent is assigned to one of the 16 contexts and is presented with two applicant profiles that differ only in our focal attribute - their level of education. Note that the applicants are substantively the same along all the characteristics in our context. Both have traveled frequently to the U.S., have lower-skilled professions, are seeking employment opportunities, and are from the same geographic region
**Note**: Here show the sample profile table shown to survey respondents.

## Adaptive design (2)

- Again, our goal here is to discover the context, c_max and c_min, where respondents are most (and least) likely to choose the applicant with a college degree over the applicant with no formal education.

- We will define our Outcome: Y_i,c=1 as equal to 1 if respondent (i) chooses the applicant with a college degree, and equal to 0 if they choose the applicant with no formal education.

- We model each respondent’s choice $Y_i$​ as a draw from a Bernoulli distribution with parameter $\theta_c$​, where $\theta_c}$​ is the unknown true probability of discrimination in context c to which the respondent was assigned. 
- For all contexts c, we assume a Beta(1, 1) prior distribution on the probability of discrimination.
- After observing the outcome $Y_i$ for respondent (i) in context c, we use Beta - Bernoulli conjugacy properties to calculate the posterior distribution for $\theta_c$

- As we discover severe discrimination in some contexts (e.g., against applicants with no formal education), we increase the probability of assigning new respondents to those contexts, resulting in uneven sample sizes but confident evidence on key contexts with high and low discrimination.

## Warmup Phase

We run our experiment in three primary phases

The first is the Warmup phase:
    - This phase is effectively a mini randomized experiment where we allocate a set number of respondents evenly across all 16 of our contexts
    - The goal of this phase is to discover initial information about the probability of discrimination in each context

## Adaptive Phase

The next is the Adaptive phase:
    - In this phase we begin adaptively searching for the contexts with the most and (least) discrimination
    - Using Thompson sampling, respondents are assigned to the context with the highest or (lowest) estimated probability of discrimination
    - As we discover severe discrimination in some contexts (e.g., against immigrants with no formal education), TS increases the probability of assigning new respondents to those contexts, resulting in uneven sample sizes but confident evidence on key contexts with high and low discrimination.

## Validation Phase

- After the adaptive phase, we have identified the context⃗s with the max and (min) expected probability of discrimination
    - However, the adaptive phase may have introduced bias into our estimates of the expected probability of discrimination in these contexts
    - To get unbiased estimates of the probability of discrimination, we carry out a final validation phase where we randomly assign a set number of respondents equally to these two chosen contexts

## Experimental Design: Overall

As an overview,
- We implement a warmup phase for a fixed number of samples,
- Then we implement an adaptive phase where we adaptively search for the max/min discriminatory contexts
- Finally, we have a validation phase where we randomly assign a fixed set of respondents to the max/min discriminatory contexts

## Experiment details

To actually implement our experiment,
- We recruited 10,000 participants via the online survey platform Prolific.
    - For the warmup phase, we allocated 2,000 respondents evenly across all 16 contexts (approximately 125 per context)
    - For the adaptive phase, we allocated 3,000 respondents to finding the context with the most discrimination; 3,000 to finding context with least discrimination, so 6,000 total
    - And then finally, we allocated 2,000 to the validation phase (so 1,000 each to the most and least discriminatory contexts)
- The survey ran across 3 days
- In order to handle continuous updating of the probability distributions for each context, we built our own custom survey and deployed it via AWS.

- And our participant demographics were
    - on average 35 years old,
    - were 68% White,
    - and were 56% female

## Results

- The following figure displays results from the Warmup+Adaptive phase and the Validation phase of our experiment. The x-axis displays the contexts⃗ that were identified in the adaptive phase as the most and least discriminatory contexts, respectively. On the y-axis is the estimated probability of discrimination within each of those contexts

- The point estimates and intervals from the warmup+adaptive phase are means and 95% credible intervals estimated from the contexts' posterior distribution of discrimination. The point estimates and intervals from the validation phase are sample means and 95% confidence intervals.

- Figure 2 illustrates that when survey respondents are asked to choose between two immigration applicants from African countries of origin, who have rarely visited the U.S. before, come from lower-skilled professions, and are seeking better employment opportunities, they will pick the candidate with a college degree approximately 77% of the time. In contrast, when choosing between two candidates from European countries, who have visited the U.S. many times, are trained in higher-skilled professions, and are seeking to escape religious persecution, they will pick the candidate with a college degree approximately 64% of the time

## Contributions

- We demonstrate how data-adaptive methods can extend beyond traditional bandit settings, where the goal is simply to select the best arm and observe the reward. In our approach, the bandit selects a context, but within that context, we still conduct a pairwise experiment by presenting respondents with two profiles—one randomly assigned to treatment and the other to control. This "mini-RCT within the bandit" is particularly useful for experimental designs like audit studies and conjoint surveys, where pairwise choices are central.
- We propose conducting adaptive experiments in social science settings using a warmup phase followed by an iterative phase.
- We update posterior probability distributions continuously throughout the experiment, instead of using a batched design.
