## Intro

Hello, I'm excited to present work on data-adaptive experimentation to find contexts with the most and least discrimination which is joint work with Jennah Gosciak and Ian Lundberg

## Experiments detect discrimination

- Randomized experiments have been shown to be effective tools for revealing discriminatory choices and studying preferences of decision makers
- Numerous studies have shown that discrimination based on background characteristics happens in many settings
- For example, audit studies on employment have demonstrated that
    - black job applicants with no criminal record receive call-backs at similar rates to white job applicants with criminal records
    - AND that job applicants who are non-mothers receive more than 2 times as many callbacks as equally qualified mothers.

## A new question

While demonstrating that discrimination exists is important, many researchers want to go beyond this and understand the dynamics of discrimination and how it varies depending on the situation

- We understand that discrimination and preferences may vary depending on background characteristics and context
- As a result of this, we argue that *in some cases* researchers should pivot to a new question that more adequately captures real-world heterogeneity
- New Q: In what settings is discrimination the most (or least) severe?

- In this work we demonstrate how adaptive experimental methods allow us to explore this heterogeneity in a more efficient manner than traditional experimental methods
- Adaptive experiments can help researchers narrow their focus to the most relevant contexts for their research question and prioritize these contexts in further experiments.
- This approach is particularly useful when used to answer questions typically reserved for experimental designs with pairwise choices, such as conjoint surveys or audit studies.
- In our experimental approach we also consider important implementation details for adaptive experiments
    - For example, we propose conducting adaptive experiments in social science settings using a warmup phase followed by an adaptive phase.
    - We also update estimated parameters continuously throughout the experiment, instead of using a batched design.

For a concrete application of this new question, we will focus on the following motivating example:

## Motivating example(1)

- Suppose that we ask U.S. citizens to choose between two immigrants’ applications for admission to the U.S. The two applicants have similar profiles with the exception of education; one applicant has a college degree and the other has no formal education. A typical experiment in this example would seek to answer the question: does having a college degree lead to greater success in terms of admission to the U.S.?

- However, we want to move beyond this question and we want to understand how discriminatory preferences for college-educated immigrants change depending on their background characteristics

## Motivating example (2)

- To explore this we'll introduce the definition of a context

- Context refers to each possible combination of applicant characteristics that may cause discrimination to vary. In our example, the four characteristics we are interested in studying are:
    - The immigrant's reason for application
    - Their county of origin
    - Their profession
    - And the number of prior trips they've taken to the U.S.
The full set of contexts is the set of all possible combinations of these characteristics.

Now, we want to measure how education-based discrimination varies across all of these contexts...

## Optimal design and limitations

However, the total number of contexts to measure discrimination quickly starts to get very large

- Even in the super simple case where each of our four different characteristics only takes on two possible values. This already results in 16 total contexts, and this number grows exponentially as the characteristics become more complex

- In a perfect world, where we have no limitations, we would run a randomized experiment for each of our 16 contexts

- If we want to effectively study discrimination in all 16 contexts one would need a sufficiently large sample size to have a robustly powered study which would also incur significant cost, not to mention it may also be challenging to implement

Given these challenges we want to pivot to a closely related but slightly different goal

## Solution - Adaptive experiments

- We no longer want to estimate discrimination in all contexts. Instead, we want to adaptively search for the context that leads to the **most** (or **least**) discrimination.
- By detecting heterogeneous discrimination, our design enables scientists and policymakers to pinpoint situations where discrimination is most and least likely to occur.

- Adaptive experiments have been used widely across economics, political science, sociology, to successfully tackle similar questions.
- The citations below note a couple papers that particularly influence our approach.

## Adaptive design (1)

- For our adaptive design, we build directly on work by Offer-Westort, and co-authors (among others). 
- We frame our experiment as a Multi-armed Bandit problem where each of our 16 contexts is an arm of the bandit
- We use the classic Thompson sampling algorithm to allocate respondents to contexts.
- After a respondent is assigned to one of the 16 contexts, they are presented with two applicant profiles that differ only in their level of education; one applicant has a college degree and one has no formal education. The applicants are substantively the same along all the other characteristics in our context. For example both are seeking to escape religious persecution, are from the same geographic region, have higher-skilled professions, and have visited the U.S. many times before

## Adaptive design (2)

- Again, our goal here is to discover the context, c_max and c_min, where respondents are most (and least) likely to choose the applicant with a college degree over the applicant with no formal education.

- We will define our Outcome: Y_i,c=1 as equal to 1 if respondent (i) chooses the applicant with a college degree, and equal to 0 if they choose the applicant with no formal education.

- We model each respondent’s choice $Y_i$​ as a draw from a Bernoulli distribution with parameter $\theta_c$​, where $\theta_c$​ is the unknown true probability of choosing the college-educated immigrant in context c to which the respondent was assigned. 
- For all contexts c, we assume a Beta(1, 1) prior distribution on this probability.
- After observing the outcome $Y_i$ for respondent (i) in context c, we use Beta - Bernoulli conjugacy properties to calculate the posterior distribution for $\theta_c$

- We can kind of think of the magnitude of discrimination in a context as the difference between theta_c and 0.5 where theta_c = 0.5 implies no discrimination; it's a 50-50 choice between the immigrant with a college education and the immigrant with no formal education.

- As we discover severe discrimination in some contexts (e.g., against applicants with no formal education), Thompson Sampling will increase the probability of assigning new respondents to those contexts, resulting in uneven sample sizes but confident evidence on key contexts with high and low discrimination.

## Experimental Design: Overall

*Warmup Phase*

We run our experiment in three primary phases

The first is the Warmup phase:
    - This phase is effectively a mini randomized experiment where we allocate a set number of respondents evenly across all 16 of our contexts
    - The goal of this phase is to discover initial information about the probability of discrimination in each context

*Adaptive Phase*

The next phase is the Adaptive phase:
    - In this phase we begin adaptively searching for the contexts with the most and (least) discrimination
    - Using Thompson sampling, respondents are assigned to the context with the highest or (lowest) estimated probability of discrimination
    - The shading of the arrows represents that as we discover strong discrimination in some contexts, TS increases the probability of assigning new respondents to those contexts, and reduces the probability of assigning respondents to the other contexts.

*Validation Phase*

Finally, the validation phase.

- The idea is that the adaptive phase is meant to be more exploratory.
- After the adaptive phase, we have identified the context⃗s with the max and (min) expected probability of discrimination
- However, the adaptive phase may have introduced bias into our estimates of discrimination in these contexts
- To get unbiased estimates of the probability of discrimination, we essentially run two randomized experiments separately on these contexts.

## Experiment details

To actually implement our experiment,
- We recruited 10,000 participants via the online survey platform Prolific.
    - For the warmup phase, we allocated 2,000 respondents evenly across all 16 contexts (approximately 125 per context)
    - For the adaptive phase, we allocated 3,000 respondents to finding the context with the most discrimination; 3,000 to finding context with least discrimination, so 6,000 total
    - And then finally, we allocated 2,000 to the validation phase (so 1,000 each to the most and least discriminatory contexts)
- The survey ran across 3 days
- In order to handle continuous updating of the probability distributions for each context, we built our own custom survey and deployed it via AWS.

- And our participant demographics were
    - on average 35 years old,
    - were 68% White,
    - and were 56% female

## Results

- The results from the experiment demonstrate that data-adaptive experiments can successfully explore heterogeneity and detect contexts with the greatest and least discrimination. This has meaningful implications for future experimental work on discrimination and decision-making.

- The following figure displays results from the Warmup+Adaptive phase and the Validation phase of our experiment. The x-axis displays the contexts⃗ that were identified in the adaptive phase as the most and least discriminatory contexts, respectively. On the y-axis is the estimated probability of discrimination within each of those contexts along with 95% confidence bands.

- This figures illustrates that when survey respondents are asked to choose between two immigration applicants from African countries of origin, who have rarely visited the U.S. before, come from lower-skilled professions, and are seeking better employment opportunities, they will pick the candidate with a college degree approximately 77% of the time. In contrast, when choosing between two candidates from European countries, who have visited the U.S. many times, are trained in higher-skilled professions, and are seeking to escape religious persecution, they will pick the candidate with a college degree approximately 64% of the time.

## Conclusion

- In conclusion, we demonstrate how adaptive experiments allow us to explore dimensions of discrimination that may be difficult to quantify with standard approaches

- This approach is especially effective for experimental designs like conjoint surveys and audit studies where pairwise choices are central.

- And along the way we demonstrate some practical implementation steps for social science researchers.