#!/bin/bash
#SBATCH -J adaptive_conjoint                # Job name
#SBATCH -o adaptive_conjoint_%j.out         # output file (%j expands to jobID)
#SBATCH -e adaptive_conjoint_%j.err         # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                  	# Request status by email
#SBATCH --mail-user=jrg377@cornell.edu   	# Email address to send results to.
#SBATCH -N 1                             	# Total number of nodes requested
#SBATCH -n 60                             	# Total number of cores requested
#SBATCH --get-user-env                   	# retrieve the users login environment
#SBATCH --mem-per-cpu=10GB                  # server memory requested (per node)
#SBATCH -t 12:00:00                       	# Time limit (hh:mm:ss)
#SBATCH --partition=default_partition       # Request partition. If you want to submit to another partition (eg, default_partition) so you have access to all faculty computers, not just ours, change this argument!
conda activate r_env
Rscript code/main.R