---
title: "Poststratification Analysis"
output: html_notebook
---

Notebook to implement and run the following analyses for the validation phase:

(1) simple mean estiamte
(2) poststratified estimate

```{r, message=F}
library(tidyverse)
library(qualtRics)
library(magrittr)
library(assertr)

knitr::opts_chunk$set(cache.extra = 2023)
config <- config::get()

source("../04_update_prob/_functions/data_cleaning.R")
```
```{r, load survey data}
# load poststratification weights from ipums acs survey
wgts <- read_csv("../02_output/ipums_strata_sizes.csv")
wgts %>%
  head()

wgts %>%
  distinct(race_acs)

# load survey data
url <- str_glue("https://{config$datacenter_id}.qualtrics.com")
survey_name <- "Political Candidates"
survey_id <- config$pol_candidates_survey_id

# can comment out after running once
# qualtrics_api_credentials(api_key = config$api_key,
#                           base_url = url,
#                           install = TRUE,
#                           overwrite=T)

df_survey <- load_qualtrics(survey_name)

nrow(df_survey)

df_survey %>%
  head()
```

```{r, drop test}
# drop earlier responses
df_survey <- df_survey %>%
  mutate(StartDate_clean = ymd_hms(StartDate)) %>%
  verify(is.na(StartDate_clean) == is.na(StartDate)) %>%
  filter(StartDate_clean >= ymd_hms("2023-12-14-00-00-00"))

nrow(df_survey)
```

```{r, validation}
# check ID uniquely identifies rows in data
stopifnot(length(unique(df_survey$`Prolific ID Q`)) == nrow(df_survey))

df_survey %>%
  distinct(Status)

# check consent means their responses are missing
df_survey %>%
  check_consent()

# check that all completed
df_survey %>%
  check_completion()

# check all are in the US
df_survey %>%
  check_location_screen()

df_survey %>%
  check_commitment()
```

## Data Cleaning
```{r}
df_clean <- clean_political_data(df_survey)

# each question number is the random ordering of the context attributes
df_clean %>%
  select(chose_younger_candidate, str_c("Q", 1:8)) %>%
  verify(!is.na(chose_younger_candidate))
```

```{r, demo vars}
df_clean %>%
  mutate(older_candidate = if_else(rnum_age <= 0.5, "Candidate 2", "Candidate 1")) %>%
  mutate(pass_attention_check = if_else(Manipulation_Q1 == older_candidate, 1, 0)) %>%
  summarize(per_pass_attention_check = mean(pass_attention_check))

df_clean %>%
  group_by(QD5) %>%
  summarize(count = n())

df_demo <- df_clean %>%
  mutate(hispanic_latino = if_else(QD4 == "Yes", 1, 0)) %>%
  mutate(female = if_else(QD5 == "Female", 1, 0)) %>%
  mutate(age = QD2_1_TEXT) %>%
  mutate(across(starts_with("QD3_"), .fns = lst(race_num = ~ if_else(!is.na(.), 1, 0)))) %>%
  mutate(
    race_count = rowSums(select(., ends_with("race_num"))),
    race = case_when(
      race_count > 1 ~ "Two or More Races",
      !is.na(QD3_1) ~ "American Indian or Alaska Native",
      !is.na(QD3_2) ~ "Asian",
      !is.na(QD3_3) ~ "Black or African American",
      !is.na(QD3_4) ~ "Native Hawaiian or Other Pacific Islander",
      !is.na(QD3_5) ~ "White",
      !is.na(QD3_6) ~ "Other",
      !is.na(QD3_7) ~ "Prefer not to disclose"
    ),
    race = factor(race, levels = c(
      "Black or African American",
      "White", "American Indian or Alaska Native",
      "Asian", "Native Hawaiian or Other Pacific Islander",
      "Other", "Two or More Races", "Prefer not to disclose"
    ))
  ) %>%
  verify(!is.na(race)) %>%
  mutate(
    race_white = if_else(race == "White", 1, 0),
    race_black = if_else(race == "Black or African American", 1, 0),
    race_aian = if_else(race == "American Indian or Alaska Native", 1, 0),
    race_asian = if_else(race == "Asian", 1, 0),
    race_nhpi = if_else(race == "Native Hawaiian or Other Pacific Islander", 1, 0),
    race_other = if_else(race == "Other", 1, 0),
    race_multi = if_else(race == "Two or More Races", 1, 0)
  )

df_demo %>%
  summarize(
    count_hispanic_latino = sum(hispanic_latino),
    per_hispanic_latino = mean(hispanic_latino)
  )

df_demo %>%
  ggplot(aes(age)) +
  geom_histogram()
```

```{r, create multiracial cat}
df_demo %>%
  group_by(race) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(per = n / sum(n)) %>%
  arrange(desc(per))
```

## Simple Mean Estimate

```{r}
df_demo %>%
  summarize(mean_chose_younger_candidate = mean(chose_younger_candidate))
```

## Poststratified Estimate
```{r}
# first, drop people who choose not to disclose for any of the demographic features
df_demo_drop <- df_demo %>%
  filter(race != "Prefer not to disclose")

# there should be 1 less category after we drop
stopifnot(length(unique(df_demo_drop$race)) == (length(unique(df_demo$race)) - 1))
```

```{r}
# running logistic regression
# dropping 'two or more race' category for multicollinearity
# other categories that don't change will be dropped as well
lm <- glm(
  formula = chose_younger_candidate ~ female + hispanic_latino + age + race, family = "binomial",
  data = df_demo_drop
)

summary(lm)
```

```{r}
# data for generating predictions for each cell
# need indicator variables for each of the factor levels
pred_df <- expand.grid(
  race = factor(
    c(
      "Black or African American",
      "White", "American Indian or Alaska Native",
      "Asian", "Native Hawaiian or Other Pacific Islander",
      "Other", "Two or More Races"
    ),
    levels = c(
      "Black or African American",
      "White", "American Indian or Alaska Native",
      "Asian", "Native Hawaiian or Other Pacific Islander",
      "Other", "Two or More Races"
    )
  ),
  female = c(1, 0),
  hispanic_latino = c(1, 0),
  age = c(18:100)
) %>%
  mutate(
    race_white = if_else(race == "White", 1, 0),
    race_black = if_else(race == "Black or African American", 1, 0),
    race_aian = if_else(race == "American Indian or Alaska Native", 1, 0),
    race_asian = if_else(race == "Asian", 1, 0),
    race_nhpi = if_else(race == "Native Hawaiian or Other Pacific Islander", 1, 0),
    race_other = if_else(race == "Other", 1, 0),
    race_multi = if_else(race == "Two or More Races", 1, 0)
  )

pred_prob_df <- cbind(pred_df,
  pred_prob = predict(lm, newdata = pred_df, type = "response")
)

pred_prob_df %>%
  head()
```

```{r, clean wgts}
# clean weight data for merging
wgts_clean <- wgts %>%
  mutate(
    hispanic_latino = if_else(hispanic == TRUE, 1, 0),
    female = if_else(sex == "Female", 1, 0),
    race = factor(race_acs, levels = c(
      "Black or African American",
      "White", "American Indian or Alaska Native",
      "Asian", "Native Hawaiian or Other Pacific Islander",
      "Other", "Two or More Races", "Prefer not to disclose"
    ))
  ) %>%
  verify(!is.na(race)) %>%
  select(race, female, hispanic_latino, age, weight)

# merge weight data onto predicted probabilties
pred_prob_df %>%
  select(race, female, hispanic_latino, age, pred_prob) %>%
  # left join bc we only want demographic groups that are truely in the population
  left_join(wgts_clean, ., by = c("race", "female", "hispanic_latino", "age")) %>%
  verify(!is.na(weight)) %>%
  # mean and weighted mean
  summarize(
    mean_pred_prob = mean(pred_prob),
    wmean_pred_prob = weighted.mean(pred_prob, weight)
  )
```






